import asyncio
from highrise import User


async def loop_emote(bot, user_id: str, emote_id: str,
                     duration: float) -> None:
    try:
        while True:
            if user_id not in bot.active_emote_loops or bot.active_emote_loops[
                    user_id]["emote_id"] != emote_id:
                break
            await bot.highrise.send_emote(emote_id, user_id)
            await asyncio.sleep(duration)
    except asyncio.CancelledError:
        pass
    except Exception as e:
        print(f"Error in loop_emote for user {user_id}: {e}")
        try:
            await bot.highrise.send_whisper(user_id,
                                            f"Error performing emote: {e}")
        except Exception as e2:
            print(f"Error sending error whisper in loop_emote: {e2}")
    finally:
        if user_id in bot.active_emote_loops and bot.active_emote_loops[
                user_id]["emote_id"] == emote_id:
            del bot.active_emote_loops[user_id]


async def stop_emote(bot, user_id: str) -> None:
    try:
        if user_id in bot.active_emote_loops:
            task = bot.active_emote_loops[user_id]["task"]
            task.cancel()
            try:
                await task
            except asyncio.CancelledError:
                pass
            del bot.active_emote_loops[user_id]
    except Exception as e:
        print(f"Error stopping emote for user {user_id}: {e}")


async def handle_emote_command(bot, user: User, message: str) -> bool:
    emote_map = {
        "rest": {"id": "sit-idle-cute", "duration": 17.062613},
        "zombie": {"id": "idle_zombie", "duration": 28.754937},
        "relaxed": {"id": "idle_layingdown2", "duration": 21.546653},
        "attentive": {"id": "idle_layingdown", "duration": 24.585168},
        "sleepy": {"id": "idle-sleep", "duration": 22.620446},
        "poutyface": {"id": "idle-sad", "duration": 24.377214},
        "posh": {"id": "idle-posh", "duration": 21.851256},
        "tired": {"id": "idle-loop-tired", "duration": 21.959007},
        "taploop": {"id": "idle-loop-tapdance", "duration": 6.261593},
        "sit": {"id": "idle-loop-sitfloor", "duration": 22.321055},
        "shy": {"id": "idle-loop-shy", "duration": 16.47449},
        "bummed": {"id": "idle-loop-sad", "duration": 6.052999},
        "chillin": {"id": "idle-loop-happy", "duration": 18.798322},
        "annoyed": {"id": "idle-loop-annoyed", "duration": 17.058522},
        "aerobics": {"id": "idle-loop-aerobics", "duration": 8.507535},
        "ponder": {"id": "idle-lookup", "duration": 22.339865},
        "heropose": {"id": "idle-hero", "duration": 21.877099},
        "relaxing": {"id": "idle-floorsleeping2", "duration": 17.253372},
        "cozynap": {"id": "idle-floorsleeping", "duration": 13.935264},
        "enthused": {"id": "idle-enthusiastic", "duration": 15.941537},
        "boogieswing": {"id": "idle-dance-swinging", "duration": 13.198551},
        "feelthebeat": {"id": "idle-dance-headbobbing", "duration": 25.367458},
        "irritated": {"id": "idle-angry", "duration": 25.427848},
        "yes": {"id": "emote-yes", "duration": 2.565001},
        "ibelieveicanfly": {"id": "emote-wings", "duration": 13.134487},
        "thewave": {"id": "emote-wave", "duration": 2.690873},
        "think": {"id": "emote-think", "duration": 3.691104},
        "theatrical": {"id": "emote-theatrical", "duration": 8.591869},
        "tapdance": {"id": "emote-tapdance", "duration": 11.057294},
        "superrun": {"id": "emote-superrun", "duration": 6.273226},
        "superpunch": {"id": "emote-superpunch", "duration": 3.751054},
        "sumofight": {"id": "emote-sumo", "duration": 10.868834},
        "thumbsuck": {"id": "emote-suckthumb", "duration": 4.185944},
        "splitsdrop": {"id": "emote-splitsdrop", "duration": 4.46931},
        "snowballfight": {"id": "emote-snowball", "duration": 5.230467},
        "snowangel": {"id": "emote-snowangel", "duration": 6.218627},
        "handshake": {"id": "emote-secrethandshake", "duration": 3.879024},
        "sad": {"id": "emote-sad", "duration": 5.411073},
        "pull": {"id": "emote-ropepull", "duration": 8.769656},
        "roll": {"id": "emote-roll", "duration": 3.560517},
        "rofl": {"id": "emote-rofl", "duration": 6.314731},
        "robot": {"id": "emote-robot", "duration": 7.607362},
        "rainbow": {"id": "emote-rainbow", "duration": 2.813373},
        "proposing": {"id": "emote-proposing", "duration": 4.27888},
        "peekaboo": {"id": "emote-peekaboo", "duration": 3.629867},
        "peace": {"id": "emote-peace", "duration": 5.755004},
        "panic": {"id": "emote-panic", "duration": 2.850966},
        "no": {"id": "emote-no", "duration": 2.703034},
        "ninjarun": {"id": "emote-ninjarun", "duration": 4.754721},
        "nightfever": {"id": "emote-nightfever", "duration": 5.488424},
        "monsterfail": {"id": "emote-monster_fail", "duration": 4.632708},
        "model": {"id": "emote-model", "duration": 6.490173},
        "flirtywave": {"id": "emote-lust", "duration": 4.655965},
        "levelup": {"id": "emote-levelup", "duration": 6.0545},
        "amused": {"id": "emote-laughing2", "duration": 5.056641},
        "laugh": {"id": "emote-laughing", "duration": 2.69161},
        "kiss": {"id": "emote-kiss", "duration": 2.387175},
        "superkick": {"id": "emote-kicking", "duration": 4.867992},
        "jump": {"id": "emote-jumpb", "duration": 3.584234},
        "judochop": {"id": "emote-judochop", "duration": 2.427442},
        "jetpack": {"id": "emote-jetpack", "duration": 16.759457},
        "hugyourself": {"id": "emote-hugyourself", "duration": 4.992751},
        "sweating": {"id": "emote-hot", "duration": 4.353037},
        "heroentrance": {"id": "emote-hero", "duration": 4.996096},
        "hello": {"id": "emote-hello", "duration": 2.734844},
        "headball": {"id": "emote-headball", "duration": 10.073119},
        "harlemshake": {"id": "emote-harlemshake", "duration": 13.558597},
        "happy": {"id": "emote-happy", "duration": 3.483462},
        "handstand": {"id": "emote-handstand", "duration": 4.015678},
        "greedyemote": {"id": "emote-greedy", "duration": 4.639828},
        "graceful": {"id": "emote-graceful", "duration": 3.7498},
        "moonwalk": {"id": "emote-gordonshuffle", "duration": 8.052307},
        "ghostfloat": {"id": "emote-ghost-idle", "duration": 19.570492},
        "gangnamstyle": {"id": "emote-gangnam", "duration": 7.275486},
        "frolic": {"id": "emote-frollicking", "duration": 3.700665},
        "faint": {"id": "emote-fainting", "duration": 18.423499},
        "clumsy": {"id": "emote-fail2", "duration": 6.475972},
        "fall": {"id": "emote-fail1", "duration": 5.617942},
        "facepalm": {"id": "emote-exasperatedb", "duration": 2.722748},
        "exasperated": {"id": "emote-exasperated", "duration": 2.367483},
        "elbowbump": {"id": "emote-elbowbump", "duration": 3.799768},
        "disco": {"id": "emote-disco", "duration": 5.366973},
        "blastoff": {"id": "emote-disappear", "duration": 6.195985},
        "faintdrop": {"id": "emote-deathdrop", "duration": 3.762728},
        "collapse": {"id": "emote-death2", "duration": 4.855549},
        "revival": {"id": "emote-death", "duration": 6.615967},
        "dab": {"id": "emote-dab", "duration": 2.717871},
        "curtsy": {"id": "emote-curtsy", "duration": 2.425714},
        "confusion": {"id": "emote-confused", "duration": 8.578827},
        "cold": {"id": "emote-cold", "duration": 3.664348},
        "charging": {"id": "emote-charging", "duration": 8.025079},
        "bunnyhop": {"id": "emote-bunnyhop", "duration": 12.380685},
        "bow": {"id": "emote-bow", "duration": 3.344036},
        "boo": {"id": "emote-boo", "duration": 4.501502},
        "homerun": {"id": "emote-baseball", "duration": 7.254841},
        "fallingapart": {"id": "emote-apart", "duration": 4.809542},
        "thumbsup": {"id": "emoji-thumbsup", "duration": 2.702369},
        "point": {"id": "emoji-there", "duration": 2.059095},
        "sneeze": {"id": "emoji-sneeze", "duration": 2.996694},
        "smirk": {"id": "emoji-smirking", "duration": 4.823158},
        "sick": {"id": "emoji-sick", "duration": 5.070367},
        "gasp": {"id": "emoji-scared", "duration": 3.008487},
        "punch": {"id": "emoji-punch", "duration": 1.755783},
        "pray": {"id": "emoji-pray", "duration": 4.503179},
        "stinky": {"id": "emoji-poop", "duration": 4.795735},
        "naughty": {"id": "emoji-naughty", "duration": 4.277602},
        "mindblown": {"id": "emoji-mind-blown", "duration": 2.397167},
        "lying": {"id": "emoji-lying", "duration": 6.313748},
        "levitate": {"id": "emoji-halo", "duration": 5.837754},
        "fireballlunge": {"id": "emoji-hadoken", "duration": 2.723709},
        "giveup": {"id": "emoji-give-up", "duration": 5.407888},
        "tummyache": {"id": "emoji-gagging", "duration": 5.500202},
        "flex": {"id": "emoji-flex", "duration": 2.099351},
        "stunned": {"id": "emoji-dizzy", "duration": 4.053049},
        "cursingemote": {"id": "emoji-cursing", "duration": 2.382069},
        "sob": {"id": "emoji-crying", "duration": 3.696499},
        "clap": {"id": "emoji-clapping", "duration": 2.161757},
        "raisetheroof": {"id": "emoji-celebrate", "duration": 3.412258},
        "arrogance": {"id": "emoji-arrogance", "duration": 6.869441},
        "angry": {"id": "emoji-angry", "duration": 5.760023},
        "voguehands": {"id": "dance-voguehands", "duration": 9.150634},
        "savagedance": {"id": "dance-tiktok8", "duration": 10.938702},
        "dontstartnow": {"id": "dance-tiktok2", "duration": 10.392353},
        "yogaflow": {"id": "dance-spiritual", "duration": 15.795092},
        "smoothwalk": {"id": "dance-smoothwalk", "duration": 6.690023},
        "ringonit": {"id": "dance-singleladies", "duration": 21.191372},
        "letsgoshopping": {"id": "dance-shoppingcart", "duration": 4.316035},
        "russian": {"id": "dance-russian", "duration": 10.252905},
        "robotic": {"id": "dance-robotic", "duration": 17.814959},
        "pennywise": {"id": "dance-pennywise", "duration": 1.214349},
        "orangejuicedance": {"id": "dance-orangejustice", "duration": 6.475263},
        "rockout": {"id": "dance-metal", "duration": 15.076377},
        "karate": {"id": "dance-martial-artist", "duration": 13.284405},
        "macarena": {"id": "dance-macarena", "duration": 12.214141},
        "handsintheair": {"id": "dance-handsup", "duration": 22.283413},
        "floss": {"id": "dance-floss", "duration": 21.329661},
        "duckwalk": {"id": "dance-duckwalk", "duration": 11.748784},
        "breakdance": {"id": "dance-breakdance", "duration": 17.623849},
        "kpopdance": {"id": "dance-blackpink", "duration": 7.150958},
        "pushups": {"id": "dance-aerobics", "duration": 8.796402},
        "hyped": {"id": "emote-hyped", "duration": 7.492423},
        "jinglebell": {"id": "dance-jinglebell", "duration": 11},
        "nervous": {"id": "idle-nervous", "duration": 21.714221},
        "toilet": {"id": "idle-toilet", "duration": 32.174447},
        "attention": {"id": "emote-attention", "duration": 4.401206},
        "astronaut": {"id": "emote-astronaut", "duration": 13.791175},
        "dancezombie": {"id": "dance-zombie", "duration": 12.922772},
        "ghost": {"id": "emoji-ghost", "duration": 3.472759},
        "hearteyes": {"id": "emote-hearteyes", "duration": 4.034386},
        "swordfight": {"id": "emote-swordfight", "duration": 5.914365},
        "timejump": {"id": "emote-timejump", "duration": 4.007305},
        "snake": {"id": "emote-snake", "duration": 5.262578},
        "heartfingers": {"id": "emote-heartfingers", "duration": 4.001974},
        "heartshape": {"id": "emote-heartshape", "duration": 6.232394},
        "hug": {"id": "emote-hug", "duration": 3.503262},
        "eyeroll": {"id": "emoji-eyeroll", "duration": 3.020264},
        "embarrassed": {"id": "emote-embarrassed", "duration": 7.414283},
        "float": {"id": "emote-float", "duration": 8.995302},
        "telekinesis": {"id": "emote-telekinesis", "duration": 10.492032},
        "sexydance": {"id": "dance-sexy", "duration": 12.30883},
        "puppet": {"id": "emote-puppet", "duration": 16.325823},
        "fighteridle": {"id": "idle-fighter", "duration": 17.19123},
        "penguindance": {"id": "dance-pinguin", "duration": 11.58291},
        "creepypuppet": {"id": "dance-creepypuppet", "duration": 6.416121},
        "sleigh": {"id": "emote-sleigh", "duration": 11.333165},
        "maniac": {"id": "emote-maniac", "duration": 4.906886},
        "energyball": {"id": "emote-energyball", "duration": 7.575354},
        "singing": {"id": "idle_singing", "duration": 10.260182},
        "frog": {"id": "emote-frog", "duration": 14.55257},
        "superpose": {"id": "emote-superpose", "duration": 4.530791},
        "cute": {"id": "emote-cute", "duration": 6.170464},
        "tiktokdance9": {"id": "dance-tiktok9", "duration": 11.892918},
        "weirddance": {"id": "dance-weird", "duration": 21.556237},
        "tiktokdance10": {"id": "dance-tiktok10", "duration": 8.225648},
        "pose7": {"id": "emote-pose7", "duration": 4.655283},
        "pose8": {"id": "emote-pose8", "duration": 4.808806},
        "casualdance": {"id": "idle-dance-casual", "duration": 9.079756},
        "pose1": {"id": "emote-pose1", "duration": 2.825795},
        "pose3": {"id": "emote-pose3", "duration": 5.10562},
        "pose5": {"id": "emote-pose5", "duration": 4.621532},
        "cutey": {"id": "emote-cutey", "duration": 3.26032},
        "punkguitar": {"id": "emote-punkguitar", "duration": 9.365807},
        "zombierun": {"id": "emote-zombierun", "duration": 9.182984},
        "fashionista": {"id": "emote-fashionista", "duration": 5.606485},
        "gravity": {"id": "emote-gravity", "duration": 8.955966},
        "icecreamdance": {"id": "dance-icecream", "duration": 14.769573},
        "wrongdance": {"id": "dance-wrong", "duration": 12.422389},
        "uwu": {"id": "idle-uwu", "duration": 24.761968},
        "tiktokdance4": {"id": "idle-dance-tiktok4", "duration": 15.500708},
        "advancedshy": {"id": "emote-shy2", "duration": 4.989278},
        "anime_dance": {"id": "dance-anime", "duration": 8.46671},
        "kawaii": {"id": "dance-kawai", "duration": 10.290789},
        "scritchy": {"id": "idle-wild", "duration": 26.422824},
        "iceskating": {"id": "emote-iceskating", "duration": 7.299156},
        "surprisebig": {"id": "emote-pose6", "duration": 5.375124},
        "celebrationstep": {"id": "emote-celebrationstep", "duration": 3.353703},
        "creepycute": {"id": "emote-creepycute", "duration": 7.902453},
        "frustrated": {"id": "emote-frustrated", "duration": 5.584622},
        "pose10": {"id": "emote-pose10", "duration": 3.989871},
        "sitrelaxed": {"id": "sit-relaxed", "duration": 29.889858},
        "laidback": {"id": "sit-open", "duration": 26.025963},
        "stargaze": {"id": "emote-stargaze", "duration": 1.127464},
        "slap": {"id": "emote-slap", "duration": 2.724945},
        "boxer": {"id": "emote-boxer", "duration": 5.555702},
        "headblowup": {"id": "emote-headblowup", "duration": 11.667537},
        "kawaiigogo": {"id": "emote-kawaiigogo", "duration": 10.0},
        "repose": {"id": "emote-repose", "duration": 1.118455},
        "tiktok7": {"id": "idle-dance-tiktok7", "duration": 12.956484},
        "shrink": {"id": "emote-shrink", "duration": 8.738784},
        "ditzypose": {"id": "emote-pose9", "duration": 4.583117},
        "teleporting": {"id": "emote-teleporting", "duration": 11.7676},
        "touch": {"id": "dance-touch", "duration": 11.7},
        "airguitar": {"id": "idle-guitar", "duration": 13.229398},
        "thisisforyou": {"id": "emote-gift", "duration": 5.8},
        "pushit": {"id": "dance-employee", "duration": 8.0},
        "sweetsmooch": {"id": "emote-kissing", "duration": 5.0},
        "tiktok11": {"id": "dance-tiktok11", "duration": 11.0},
        "cutesalute": {"id": "emote-cutesalute", "duration": 3.0},
        "salut": {"id": "emote-salute", "duration": 3.0},
        "uhmmm": {"id": "emote-thought", "duration": 27.431847},
        "crouch": {"id": "idle-crouched", "duration": 28.274845},
        "wait": {"id": "dance-wait", "duration": 9.924913},
        "ignitionboost": {"id": "hcc-jetpack", "duration": 27.447751},
        "shush": {"id": "emoji-shush", "duration": 3.399787},
        "tough": {"id": "idle_tough", "duration": 28.643417},
        "fail3": {"id": "emote-fail3", "duration": 7.062429},
        "shocked": {"id": "emote-shocked", "duration": 5.588654},
        "theatricaltest": {"id": "emote-theatrical-test", "duration": 10.855672},
        "fireworks": {"id": "emote-fireworks", "duration": 13.147647},
        "electrified": {"id": "emote-electrified", "duration": 5.287879},
        "headless": {"id": "idle-headless", "duration": 41.802306},
        "armcannon": {"id": "emote-armcannon", "duration": 8.674283},
        "tiktok4": {"id": "dance-tiktok4", "duration": 15.003275},
        "donttouch": {"id": "dance-tiktok13", "duration": 9.240415},
        "hiphop": {"id": "dance-hiphop", "duration": 27.589143},
        "hopscotch": {"id": "emote-hopscotch", "duration": 5.839895},
        "outfit2": {"id": "emote-outfit2", "duration": 11.944829},
        "pose12": {"id": "emote-pose12", "duration": 5.806148},
        "fading": {"id": "emote-fading", "duration": 14.052651},
        "pose13": {"id": "emote-pose13", "duration": 6.385457},
        "breakscreen": {"id": "profile-breakscreen", "duration": 10.700304},
        "surf": {"id": "emote-surf", "duration": 19.009833},
        "cartwheel": {"id": "emote-cartwheel", "duration": 7.935524},
        "kissingpassionate": {"id": "emote-kissing-passionate", "duration": 10.469552},
        "tiktok1": {"id": "dance-tiktok1", "duration": 12.415152},
        "runvertical": {"id": "run-vertical", "duration": 3.864336},
        "flirt": {"id": "emote-flirt", "duration": 7.952305},
        "disappointed": {"id": "emote-receive-disappointed", "duration": 7.139604},
        "gooey": {"id": "emote-gooey", "duration": 5.819651},
        "oops": {"id": "emote-oops", "duration": 8.021011},
        "walkvertical": {"id": "walk-vertical", "duration": 4.179899},
        "thief": {"id": "emote-thief", "duration": 6.885812},
        "sheephop": {"id": "emote-sheephop", "duration": 3.778883},
        "runhop": {"id": "emote-runhop", "duration": 8.723231},
        "tiktok15": {"id": "dance-tiktok15", "duration": 16.105051},
        "giftreceived": {"id": "emote-receive-happy", "duration": 5.941981},
        "tiktok6": {"id": "dance-tiktok6", "duration": 11.991088},
        "confused2": {"id": "emote-confused2", "duration": 10.056858},
        "musclepose": {"id": "emote-pose4", "duration": 6.080044},
        "dinner": {"id": "emote-dinner", "duration": 14.245902},
        "wavey": {"id": "emote-wavey", "duration": 12.597289},
        "pose2": {"id": "emote-pose2", "duration": 7.204309},
        "shuffle": {"id": "dance-shuffle", "duration": 9.046641},
        "twitched": {"id": "emote-twitched", "duration": 9.609788},
        "juggling": {"id": "emote-juggling", "duration": 5.831046},
        "idletiktok6": {"id": "idle-dance-tiktok6", "duration": 9.730481},
        "opera": {"id": "emote-opera", "duration": 5.761024},
        "tiktok3": {"id": "dance-tiktok3", "duration": 10.403667},
        "kid": {"id": "dance-kid", "duration": 10.302606},
        "anime3": {"id": "dance-anime3", "duration": 12.374316},
        "tiktok16": {"id": "dance-tiktok16", "duration": 11.019992},
        "pokedance": {"id": "dance-tiktok12", "duration": 14.846371},
        "tiktok5": {"id": "dance-tiktok5", "duration": 12.202406},
        "coldidle": {"id": "idle-cold", "duration": 17.712922},
        "pose11": {"id": "emote-pose11", "duration": 5.113470},
        "handwalk": {"id": "emote-handwalk", "duration": 7.772777},
        "dramatic": {"id": "emote-dramatic", "duration": 9.103327},
        "outfit": {"id": "emote-outfit", "duration": 13.197255},
        "phone": {"id": "idle-phone", "duration": 31.364736},
        "sitchair": {"id": "sit-chair", "duration": 3.299018},
        "space": {"id": "idle-space", "duration": 37.784958},
        "mine": {"id": "mining-mine", "duration": 5.022986},
        "miningsuccess": {"id": "mining-success", "duration": 3.105142},
        "miningfail": {"id": "mining-fail", "duration": 3.411112},
        "fishingpull": {"id": "fishing-pull", "duration": 2.809936},
        "fishing": {"id": "fishing-idle", "duration": 17.870053},
        "fishingcast": {"id": "fishing-cast", "duration": 2.820928},
        "catch": {"id": "fishing-pull-small", "duration": 3.669087},
        "hipshake": {"id": "dance-hipshake", "duration": 13.383699},
        "fruity": {"id": "dance-fruity", "duration": 18.252850},
        "cheer": {"id": "dance-cheerleader", "duration": 17.928509},
        "magnetic": {"id": "dance-tiktok14", "duration": 11.197176},
        "blowkisses": {"id": "emote-blowkisses", "duration": 5.978925},
        "fairytwirl": {"id": "emote-looping", "duration": 9.886148},
        "fairyfloat": {"id": "idle-floating", "duration": 27.596596},
        "karma": {"id": "dance-wild", "duration": 16.250530},
        "moonlithowl": {"id": "emote-howl", "duration": 8.101369},
        "howl": {"id": "idle-howl", "duration": 48.618348},
        "trampoline": {"id": "emote-trampoline", "duration": 6.105925},
        "launch": {"id": "emote-launch", "duration": 10.881689},
        "stargazing": {"id": "emote-stargazer", "duration": 7.928274},
        "hotcocoa": {"id": "emote-holding-hot-cocoa", "duration": 3.873471},
        "mittens": {"id": "emote-mittens", "duration": 3.169820}
    }

    if message.lower().strip() in emote_map:
        try:
            emote = emote_map[message.lower().strip()]
            emote_id = emote["id"]
            duration = emote["duration"]
            if user.id in bot.active_emote_loops:
                await stop_emote(bot, user.id)
            task = asyncio.create_task(
                loop_emote(bot, user.id, emote_id, duration))
            bot.active_emote_loops[user.id] = {
                "task": task,
                "emote_id": emote_id
            }
            await bot.highrise.send_whisper(
                user.id,
                f"Starting emote loop for {message}. Type 'stop' to end.")
            await asyncio.sleep(0.5)
            return True
        except Exception as e:
            await bot.highrise.send_whisper(
                user.id, f"Error starting emote loop for {message}: {e}")
            print(f"Emote loop error: {e}")
        return True
